INSERT INTO TBL_PRODUCTOS (NOMBRE, PRECIO, CREATED_AT) VALUES ('TV PANASONIC',2500000, NOW());
INSERT INTO TBL_PRODUCTOS (NOMBRE, PRECIO, CREATED_AT) VALUES ('Nevera LG',1500000, NOW());
INSERT INTO TBL_PRODUCTOS (NOMBRE, PRECIO, CREATED_AT) VALUES ('Mouse',25000, NOW());
INSERT INTO TBL_PRODUCTOS (NOMBRE, PRECIO, CREATED_AT) VALUES ('Qida Cat',3800, NOW());
INSERT INTO TBL_PRODUCTOS (NOMBRE, PRECIO, CREATED_AT) VALUES ('Jabon Fab', 1750, NOW());
INSERT INTO TBL_PRODUCTOS (NOMBRE, PRECIO, CREATED_AT) VALUES ('Sombrilla',8500, NOW());
INSERT INTO TBL_PRODUCTOS (NOMBRE, PRECIO, CREATED_AT) VALUES ('Lapicero',1250, NOW());
INSERT INTO TBL_PRODUCTOS (NOMBRE, PRECIO, CREATED_AT) VALUES ('TV PANASONIC',2500000, NOW());
